// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        (unknown)
// source: noble/jester/v1/jester.proto

package jester

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dollar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vaas          [][]byte               `protobuf:"bytes,1,rep,name=vaas,proto3" json:"vaas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dollar) Reset() {
	*x = Dollar{}
	mi := &file_noble_jester_v1_jester_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dollar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dollar) ProtoMessage() {}

func (x *Dollar) ProtoReflect() protoreflect.Message {
	mi := &file_noble_jester_v1_jester_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dollar.ProtoReflect.Descriptor instead.
func (*Dollar) Descriptor() ([]byte, []int) {
	return file_noble_jester_v1_jester_proto_rawDescGZIP(), []int{0}
}

func (x *Dollar) GetVaas() [][]byte {
	if x != nil {
		return x.Vaas
	}
	return nil
}

var File_noble_jester_v1_jester_proto protoreflect.FileDescriptor

var file_noble_jester_v1_jester_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2f, 0x6a, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x76,
	0x31, 0x2f, 0x6a, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x6a, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22,
	0x1c, 0x0a, 0x06, 0x44, 0x6f, 0x6c, 0x6c, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x61,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x76, 0x61, 0x61, 0x73, 0x42, 0x1d, 0x5a,
	0x1b, 0x6a, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x78, 0x79,
	0x7a, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x6a, 0x65, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_noble_jester_v1_jester_proto_rawDescOnce sync.Once
	file_noble_jester_v1_jester_proto_rawDescData = file_noble_jester_v1_jester_proto_rawDesc
)

func file_noble_jester_v1_jester_proto_rawDescGZIP() []byte {
	file_noble_jester_v1_jester_proto_rawDescOnce.Do(func() {
		file_noble_jester_v1_jester_proto_rawDescData = protoimpl.X.CompressGZIP(file_noble_jester_v1_jester_proto_rawDescData)
	})
	return file_noble_jester_v1_jester_proto_rawDescData
}

var file_noble_jester_v1_jester_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_noble_jester_v1_jester_proto_goTypes = []any{
	(*Dollar)(nil), // 0: noble.jester.v1.Dollar
}
var file_noble_jester_v1_jester_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_noble_jester_v1_jester_proto_init() }
func file_noble_jester_v1_jester_proto_init() {
	if File_noble_jester_v1_jester_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_noble_jester_v1_jester_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_noble_jester_v1_jester_proto_goTypes,
		DependencyIndexes: file_noble_jester_v1_jester_proto_depIdxs,
		MessageInfos:      file_noble_jester_v1_jester_proto_msgTypes,
	}.Build()
	File_noble_jester_v1_jester_proto = out.File
	file_noble_jester_v1_jester_proto_rawDesc = nil
	file_noble_jester_v1_jester_proto_goTypes = nil
	file_noble_jester_v1_jester_proto_depIdxs = nil
}
