// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        (unknown)
// source: noble/jester/v1/query.proto

package jester

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVoteExtensionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVoteExtensionRequest) Reset() {
	*x = GetVoteExtensionRequest{}
	mi := &file_noble_jester_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVoteExtensionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoteExtensionRequest) ProtoMessage() {}

func (x *GetVoteExtensionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noble_jester_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoteExtensionRequest.ProtoReflect.Descriptor instead.
func (*GetVoteExtensionRequest) Descriptor() ([]byte, []int) {
	return file_noble_jester_v1_query_proto_rawDescGZIP(), []int{0}
}

type GetVoteExtensionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dollar        *Dollar                `protobuf:"bytes,1,opt,name=dollar,proto3" json:"dollar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVoteExtensionResponse) Reset() {
	*x = GetVoteExtensionResponse{}
	mi := &file_noble_jester_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVoteExtensionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoteExtensionResponse) ProtoMessage() {}

func (x *GetVoteExtensionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noble_jester_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoteExtensionResponse.ProtoReflect.Descriptor instead.
func (*GetVoteExtensionResponse) Descriptor() ([]byte, []int) {
	return file_noble_jester_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *GetVoteExtensionResponse) GetDollar() *Dollar {
	if x != nil {
		return x.Dollar
	}
	return nil
}

var File_noble_jester_v1_query_proto protoreflect.FileDescriptor

var file_noble_jester_v1_query_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2f, 0x6a, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x76,
	0x31, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6e,
	0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x6a, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2f, 0x6a, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f,
	0x6a, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x19, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x56, 0x6f,
	0x74, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x64, 0x6f, 0x6c, 0x6c, 0x61, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x6a, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x6c, 0x6c, 0x61, 0x72, 0x52, 0x06, 0x64, 0x6f,
	0x6c, 0x6c, 0x61, 0x72, 0x32, 0x77, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x6e, 0x6f, 0x62, 0x6c, 0x65,
	0x2e, 0x6a, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6f,
	0x74, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x6a, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1d, 0x5a,
	0x1b, 0x6a, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x2e, 0x78, 0x79,
	0x7a, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x6a, 0x65, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_noble_jester_v1_query_proto_rawDescOnce sync.Once
	file_noble_jester_v1_query_proto_rawDescData = file_noble_jester_v1_query_proto_rawDesc
)

func file_noble_jester_v1_query_proto_rawDescGZIP() []byte {
	file_noble_jester_v1_query_proto_rawDescOnce.Do(func() {
		file_noble_jester_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_noble_jester_v1_query_proto_rawDescData)
	})
	return file_noble_jester_v1_query_proto_rawDescData
}

var file_noble_jester_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_noble_jester_v1_query_proto_goTypes = []any{
	(*GetVoteExtensionRequest)(nil),  // 0: noble.jester.v1.GetVoteExtensionRequest
	(*GetVoteExtensionResponse)(nil), // 1: noble.jester.v1.GetVoteExtensionResponse
	(*Dollar)(nil),                   // 2: noble.jester.v1.Dollar
}
var file_noble_jester_v1_query_proto_depIdxs = []int32{
	2, // 0: noble.jester.v1.GetVoteExtensionResponse.dollar:type_name -> noble.jester.v1.Dollar
	0, // 1: noble.jester.v1.QueryService.GetVoteExtension:input_type -> noble.jester.v1.GetVoteExtensionRequest
	1, // 2: noble.jester.v1.QueryService.GetVoteExtension:output_type -> noble.jester.v1.GetVoteExtensionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_noble_jester_v1_query_proto_init() }
func file_noble_jester_v1_query_proto_init() {
	if File_noble_jester_v1_query_proto != nil {
		return
	}
	file_noble_jester_v1_jester_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_noble_jester_v1_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noble_jester_v1_query_proto_goTypes,
		DependencyIndexes: file_noble_jester_v1_query_proto_depIdxs,
		MessageInfos:      file_noble_jester_v1_query_proto_msgTypes,
	}.Build()
	File_noble_jester_v1_query_proto = out.File
	file_noble_jester_v1_query_proto_rawDesc = nil
	file_noble_jester_v1_query_proto_goTypes = nil
	file_noble_jester_v1_query_proto_depIdxs = nil
}
